/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.password.validator

import arrow.core.getOrHandle

fun main() {
    val passwordPolicy = AllPasswordPolicy(
        PasswordMustBeAtLeast8Characters(),
        PasswordMustContainAtLeast2Numbers(),
        PasswordMustContainAtLeastOneCapitalLetter(),
    )
    val factory = Password.Factory(passwordPolicy)
    val password = factory.create("Hello-World-1234")
        .getOrHandle { throw IllegalArgumentException(it.joinToString()) }

    println(password)
}
