/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.password.validator

import arrow.core.computations.either

suspend fun main() {
    val result = either<FailedReasons, Password> {
        val passwordPolicy = AllPasswordPolicy(
            PasswordMustBeAtLeast8Characters(),
            PasswordMustContainAtLeast2Numbers(),
            PasswordMustContainAtLeastOneCapitalLetter(),
            PasswordMustContainAtLeastOneSpecialCharacter(),
        )
        val factory = Password.Factory(passwordPolicy)
        val password = factory.create("Hello-World-1234!").bind()

        password
    }

    println(result)
}
