/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.fractional.expression

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class AppTest : StringSpec({
    "strings.length should return size of string" {
        "hello".length shouldBe 5
    }
})
