/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.fractional.expression

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class FitsTest : StringSpec({
    "1x1" {
        val base = """
            y
        """.trimIndent()

        val target = """
            x
        """.trimIndent()

        val expected = """
            x
        """.trimIndent()

        Fits.width(target, base) shouldBe expected
    }
})
