/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.fractional.expression

import com.github.lette1394.fractional.expression.Fits.fit
import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe

class FitsTest : FreeSpec({
    "width" - {
        "1x1" {
            val target = """
                x
            """.trimIndent()

            val base = """
                y
            """.trimIndent()

            val expected = """
                x
            """.trimIndent()

            target fit base shouldBe expected
        }

        "1x2" {
            val target = """
                x
            """.trimIndent()

            val base = """
                y
                y
            """.trimIndent()

            val expected = """
                 
                x
            """.trimIndent()

            target fit base shouldBe expected
        }

        "1x2 reverse" {
            val target = """
                x
                x
            """.trimIndent()

            val base = """
                y
            """.trimIndent()

            val expected = """
                x
                x
            """.trimIndent()

            target fit base shouldBe expected
        }

        "2x2" {
            val target = """
                x
                x
            """.trimIndent()

            val base = """
                y
                y
            """.trimIndent()

            val expected = """
                x
                x
            """.trimIndent()

            target fit base shouldBe expected
        }

        "1x3" {
            val target = """
                x
            """.trimIndent()

            val base = """
                y
                y
                y
            """.trimIndent()

            val expected = """
                 
                x
                 
            """.trimIndent()

            target fit base shouldBe expected
        }
    }
})
